ruby '~> 2.6.3'
source "https://rubygems.org"

gem "bundler", "=2.1.4"
gem "cocoapods", "1.9.1"
gem "fastlane", "2.146.1"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
