# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs Android (Native) unit tests"
  lane :test do
    gradle(task: "test")
  end

  JS_PACKAGE = load_json(json_path: "../package.json")

  desc "Build a Beta APK and AAB"
  lane :staging do
    gradle(
      task: "clean assembleStagingDebug",
      print_command: false,
    )
  end 

  desc "Build a Beta APK and AAB"
  lane :beta do

    increment_version_code(
      gradle_file_path: "../android/app/build.gradle",
    )

    increment_version_name(
      gradle_file_path: "../android/app/build.gradle",
      version_name: JS_PACKAGE['version']
    )

    gradle(
      task: "assemble",
      build_type: "prodRelease",
      print_command: false,
      properties: {
        "PRIVATEKIT_RELEASE_STORE_FILE" => ENV["secrets.SIGNING_KEY"],
        "PRIVATEKIT_RELEASE_STORE_PASSWORD"  => ENV["secrets.KEY_STORE_PASSWORD"],
        "PRIVATEKIT_RELEASE_KEY_ALIAS" => ENV["secrets.KEY_ALIAS"],
        "PRIVATEKIT_RELEASE_KEY_PASSWORD" => ENV["secrets.KEY_PASSWORD"],
      }
    )

    gradle(
      task: "bundle",
      build_type: "prodRelease",
      print_command: false,
      properties: {
        "PRIVATEKIT_RELEASE_STORE_FILE" => ENV["secrets.SIGNING_KEY"],
        "PRIVATEKIT_RELEASE_STORE_PASSWORD"  => ENV["secrets.KEY_STORE_PASSWORD"],
        "PRIVATEKIT_RELEASE_KEY_ALIAS" => ENV["secrets.KEY_ALIAS"],
        "PRIVATEKIT_RELEASE_KEY_PASSWORD" => ENV["secrets.KEY_PASSWORD"],
      }
    )

    validate_play_store_json_key(
      json_key: "app/json_key.json",
    )
    
    upload_to_play_store(
      track: 'beta',
      aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH],
    )
  end
end
